### ISSUE TITLE
文字稿

### ISSUE THREAD

**Issue by tsaiweiche** [SuiSiann/SuiSiann-BangTsam#23]
您好，

想請問在哪邊可以找到音檔對應的文字稿呢？

**Comment by sih4sing5hong5** [comment]
Gâu-tsá，整理好勢ê資料tī https://suisiann-dataset.ithuan.tw

**Comment by tsaiweiche** [comment]
歹勢 我猶是揣無link ，
我 下載 這的 link， https://www.dropbox.com/s/rye2sd0wo718bj5/SuiSiann-0.2.1.tar?dl=0 
ah-m̄-kò  lāi-té bô  transcript

**Comment by tsaiweiche** [comment]
It' s very weird, I use another computer to download file from same link.
It shows transcripts now.
Anyway, Thanks for your reply. It is fine now.
